### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by afrubin** [mikldk/malan#11]
The `tests` directory was not installed so I am unable to run the automated tests locally using `testthat`.

```
> ls /Library/Frameworks/R.framework/Versions/3.4/Resources/library/malan/
CITATION	INDEX		Meta		R		doc		html
DESCRIPTION	LICENSE		NAMESPACE	data		help		libs
```

**Comment by mikldk** [comment]
You need to use `test_package()`. I have included these instructions in the README in d047767e2dc775e36ed6706b0f540b1f48e2c5b9.

**Comment by mikldk** [comment]
I.e. `test_package('malan')`.

**Comment by mikldk** [comment]
Don't you get something with a number of tests run and no errors? I got two lines with that.

**Comment by afrubin** [comment]
No, I just get:
```
> test_package('malan')
>
```
I'll report back once the latest gcc has finished building and I have reinstalled the package.

**Comment by mikldk** [comment]
I get:
```
> test_package('malan')
 ══ testthat results  ═════════════════
OK: 310 SKIPPED: 0 FAILED: 0
```
