### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ajank** [mikldk/malan#3]
Please consider making an issue regarding the memory leak mentioned here.
https://github.com/mikldk/malan/blob/c975534210d1f39a2de040f0f883765a1b3ab0ba/src/malan_types.h#L16
It might be e.g. helpful for the users to know which functions might be leaking. If you have some suspicions regarding what is causing it, this would be a place to note them down. ;)

**Comment by mikldk** [comment]
@ajank , what do you think about #6 suggetion?

**Comment by mikldk** [comment]
Fixed by #6
