### ISSUE TITLE
Make some parameter names more intuitive 

### ISSUE THREAD

**Issue by ajank** [mikldk/malan#4]
Consider renaming `extra_generations_full` (by default `0L`) to `generations_full` (by default `1L`).
https://github.com/mikldk/malan/blob/a022a04040c9cd8b147c2c68a480a1a8e7cf0ca3/R/RcppExports.R#L88

**Comment by mikldk** [comment]
I maybe think this is a matter of taste. I am not sure if your suggested naming is more clear? Do you think it is? I am willing to break the API if there is good reasons to it :-). Will more elaborate documentation help?

**Comment by mikldk** [comment]
What about maybe adding the parameter `generations_full` with default value `1`. And then ensure that only one of these are specified?

**Comment by mikldk** [comment]
I have given it some additional thoughts and think you are right. I will consider it some more and probably try to update the API and vignette.
