### ISSUE TITLE
Tests not checked by Travis CI

### ISSUE THREAD

**Issue by ajank** [mikldk/malan#8]
I'm not 100% sure, but it seems to me that Travis CI does not run the unit tests. I'd expect something like
```
* checking tests ...
  Running "test-autosomal.R"
  ...
```
in Travis' log, but I couldn't find anything like that.

I was also happy to see that all the tests succeed locally for me.

**Comment by mikldk** [comment]
I am quite sure they are run. See e.g. the latest log for release <https://travis-ci.org/mikldk/malan/jobs/373697136> on L1427 "Running ‘testthat.R’". And the coverage at <https://codecov.io/gh/mikldk/malan> is done by the CI framework. 
And in `testthat` there is a `skip_on_travis()` (<https://github.com/r-lib/testthat/blob/master/R/skip.R>) so I would think that all is okay.

But I must admit that I am still quite new in this Travis business, so I may be wrong.

**Comment by ajank** [comment]
You are right, it was there all the time! Also, the coverage charts prove the point (and I'm also quite new to Travis, wasn't aware of codecov.io!). Many thanks for explaining this, I'm closing the issue.

**Comment by mikldk** [comment]
Exactly. It is very convenient, as `gcov` can be difficult (or slow) to run at your own computer. Thanks.
